addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
cache:
  directories:
    - $HOME/.cache/rebar3
    - $TRAVIS_BUILD_DIR/_build
env:
  - CC=gcc-5
install: true
language: erlang
notifications:
  email: false
otp_release:
  - 21.0.2
  - 20.3
  - 19.3
  - 18.3
script: 
- ./bin/rebar3 update
- make travis
sudo: false
